version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"

volumes:
  db-data:
