// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testInventoryItems(t *testing.T) {
	t.Parallel()

	query := InventoryItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testInventoryItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInventoryItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := InventoryItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInventoryItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InventoryItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInventoryItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := InventoryItemExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if InventoryItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected InventoryItemExists to return true, but got false.")
	}
}

func testInventoryItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	inventoryItemFound, err := FindInventoryItem(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if inventoryItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testInventoryItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = InventoryItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testInventoryItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := InventoryItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testInventoryItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	inventoryItemOne := &InventoryItem{}
	inventoryItemTwo := &InventoryItem{}
	if err = randomize.Struct(seed, inventoryItemOne, inventoryItemDBTypes, false, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}
	if err = randomize.Struct(seed, inventoryItemTwo, inventoryItemDBTypes, false, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = inventoryItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = inventoryItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InventoryItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testInventoryItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	inventoryItemOne := &InventoryItem{}
	inventoryItemTwo := &InventoryItem{}
	if err = randomize.Struct(seed, inventoryItemOne, inventoryItemDBTypes, false, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}
	if err = randomize.Struct(seed, inventoryItemTwo, inventoryItemDBTypes, false, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = inventoryItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = inventoryItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func inventoryItemBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func inventoryItemAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InventoryItem) error {
	*o = InventoryItem{}
	return nil
}

func testInventoryItemsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &InventoryItem{}
	o := &InventoryItem{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize InventoryItem object: %s", err)
	}

	AddInventoryItemHook(boil.BeforeInsertHook, inventoryItemBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	inventoryItemBeforeInsertHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.AfterInsertHook, inventoryItemAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	inventoryItemAfterInsertHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.AfterSelectHook, inventoryItemAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	inventoryItemAfterSelectHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.BeforeUpdateHook, inventoryItemBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	inventoryItemBeforeUpdateHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.AfterUpdateHook, inventoryItemAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	inventoryItemAfterUpdateHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.BeforeDeleteHook, inventoryItemBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	inventoryItemBeforeDeleteHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.AfterDeleteHook, inventoryItemAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	inventoryItemAfterDeleteHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.BeforeUpsertHook, inventoryItemBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	inventoryItemBeforeUpsertHooks = []InventoryItemHook{}

	AddInventoryItemHook(boil.AfterUpsertHook, inventoryItemAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	inventoryItemAfterUpsertHooks = []InventoryItemHook{}
}

func testInventoryItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInventoryItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(inventoryItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInventoryItemToManyInventoryLevels(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a InventoryItem
	var b, c InventoryLevel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, inventoryLevelDBTypes, false, inventoryLevelColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, inventoryLevelDBTypes, false, inventoryLevelColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.InventoryItemID = a.ID
	c.InventoryItemID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.InventoryLevels().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.InventoryItemID == b.InventoryItemID {
			bFound = true
		}
		if v.InventoryItemID == c.InventoryItemID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := InventoryItemSlice{&a}
	if err = a.L.LoadInventoryLevels(ctx, tx, false, (*[]*InventoryItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.InventoryLevels); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.InventoryLevels = nil
	if err = a.L.LoadInventoryLevels(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.InventoryLevels); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testInventoryItemToManyAddOpInventoryLevels(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a InventoryItem
	var b, c, d, e InventoryLevel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, inventoryItemDBTypes, false, strmangle.SetComplement(inventoryItemPrimaryKeyColumns, inventoryItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*InventoryLevel{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, inventoryLevelDBTypes, false, strmangle.SetComplement(inventoryLevelPrimaryKeyColumns, inventoryLevelColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*InventoryLevel{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddInventoryLevels(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.InventoryItemID {
			t.Error("foreign key was wrong value", a.ID, first.InventoryItemID)
		}
		if a.ID != second.InventoryItemID {
			t.Error("foreign key was wrong value", a.ID, second.InventoryItemID)
		}

		if first.R.InventoryItem != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.InventoryItem != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.InventoryLevels[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.InventoryLevels[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.InventoryLevels().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testInventoryItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInventoryItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InventoryItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInventoryItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InventoryItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	inventoryItemDBTypes = map[string]string{`ID`: `bigint`, `Cost`: `decimal`, `CountryCodeOfOrigin`: `varchar`, `CreatedAt`: `datetime`, `ProvinceCodeOfOrigin`: `varchar`, `RequiresShipping`: `tinyint`, `Sku`: `varchar`, `Tracked`: `tinyint`, `UpdatedAt`: `datetime`}
	_                    = bytes.MinRead
)

func testInventoryItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(inventoryItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(inventoryItemAllColumns) == len(inventoryItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testInventoryItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(inventoryItemAllColumns) == len(inventoryItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InventoryItem{}
	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, inventoryItemDBTypes, true, inventoryItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(inventoryItemAllColumns, inventoryItemPrimaryKeyColumns) {
		fields = inventoryItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			inventoryItemAllColumns,
			inventoryItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := InventoryItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testInventoryItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(inventoryItemAllColumns) == len(inventoryItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLInventoryItemUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := InventoryItem{}
	if err = randomize.Struct(seed, &o, inventoryItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InventoryItem: %s", err)
	}

	count, err := InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, inventoryItemDBTypes, false, inventoryItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InventoryItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InventoryItem: %s", err)
	}

	count, err = InventoryItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
